name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    name: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: yarn install, build, test and publish
        run: |
          yarn install
          yarn build
          yarn test
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
